apiVersion: v1
kind: Secret
metadata:
  name: demo-app-priv-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ajaragz/k8s-argocd.git
  username: ajaragz
  password: GITHUB_TOKEN