apiVersion: v1
kind: Secret
metadata:
  name: demo-app-priv-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nstrlabs/proof-sre-candidate-angel-jara.git
  username: not-used
  password: GITHUB_TOKEN