apiVersion: v1
kind: Service
metadata:
  name: temp-conversion-service
spec:
  selector:
    app: temp-conversion-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP