name: Build and Push app container images

# This pipeline builds and pushes the component's images
#
# A couple of simplifications are used that should not be used in
# real environments:
# - Pipeline build number is used as image tag, which couples versioning to the CI
# - All component's use the same version

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_TAG: 0.0.${{ github.run_number }}

    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web-ui image
        run: ./build_push.sh web-ui

      - name: Build and push weather-service image
        run: ./build_push.sh weather-service

      - name: Build and push temp-conversion-service image
        run: ./build_push.sh temp-conversion-service
